source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'WordPressApiExample' do
 pod "WordPressApi", :path => "../"
end

target 'Tests' do
 pod 'OHHTTPStubs', '4.7.1'
 pod "WordPressApi", :path => "../"
end

