source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'WordPressApiExample' do
  pod 'WordPressApi', :path => '../'

  target 'Tests' do
    pod 'OHHTTPStubs', '4.7.1'
  end
end
